rk-mpp-service-objs := mpp_service.o
rk-mpp-device-objs := mpp_dev_common.o mpp_iommu_dma.o
rk-mpp-rkvdec-objs := mpp_dev_rkvdec.o

obj-$(CONFIG_ROCKCHIP_MPP_SERVICE) += rk-mpp-service.o
obj-$(CONFIG_ROCKCHIP_MPP_DEVICE) += rk-mpp-device.o
obj-$(CONFIG_ROCKCHIP_MPP_RKVDEC_DEVICE) += rk-mpp-rkvdec.o
